### ISSUE TITLE
auro-popover: popover content overflows border

### ISSUE THREAD

**Issue by Dayna-A** [AlaskaAirlines/auro-popover#32]
## Describe the bug

Popover used within a parent that has 'nowrap' set causes popover content to overflow popover borders.

## To Reproduce

1. Insert latest popover version with a large chunk of text as content into a parent element that has 'no wrap' set on it.
2. On hover - content Text overflows the popover background and border on the right side.

## Expected behavior

Popover box is large enough to contain the content text OR Popover box keeps content from being larger than box.

## Screenshots

![image](https://user-images.githubusercontent.com/35708093/125010077-acee4500-e01a-11eb-8a63-48ba46b3bc98.png)

## Desktop (please complete the following information):

- OS: macOS Big Sur 11.2.3
 - Browser: Chrome  91.0.4472.114 
 - Popover 3.1.1

## Additional context

Problem seems to resolve when percentage based max- width for popover are removed OR when the nowrap on the parent element is removed.

![image](https://user-images.githubusercontent.com/35708093/125010290-15d5bd00-e01b-11eb-949d-a2d9aedb9c66.png)

![image](https://user-images.githubusercontent.com/35708093/125010349-330a8b80-e01b-11eb-9487-0824b8aa8322.png)

**Comment by jason-capsule42** [comment]
The issue is that in a previous release we added a max-width to the popover content. However, we did not add any CSS rules that would force the slot content to render with the same max-width.

Anything that has a rendering baseline larger than the popover's content max-width will fail. This means that long strings with the rule 'whitespace: nowrap;', images with a width that is wider, tables with wide/many columns, etc. will overflow the popover content.

My initial thought is that the slot content CSS should have the same `max-width` or `width: 100%' rule(s).

```css
.popover {
  ::slotted {
    width: 100%;
  }
}
```

Doing so should make the slotted content render correctly for clipping/whitespace wrapping and prevent the overflow demonstrated in the original ticket.
